apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular-k8-deploy
  template:
    metadata:
      labels:
        app: angular-k8-deploy
    spec:
      containers:
        - name: frontend-angular-build
          image: gauti019/ci-cd:v3
          imagePullPolicy: Always
          ports:
            - containerPort: 80
